In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Sort the CSV you saved creaded in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Airai,TL,2020-04-14 04:46:25,-8.93,125.41,69.57,64,91,2.93
1,1,Ushuaia,AR,2020-04-14 04:46:25,-54.80,-68.30,46.40,65,75,9.17
2,2,Hilo,US,2020-04-14 04:46:26,19.73,-155.09,78.80,74,20,10.29
3,3,Rikitea,PF,2020-04-14 04:42:39,-23.12,-134.97,77.02,69,81,12.01
4,4,Negara,ID,2020-04-14 04:46:26,-8.32,114.60,84.38,68,11,7.94

In [3]:
# Get the data types. (gmaps uses only integer or floating point data)
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

# 1. Assign the locations to an array of latitude and logitude pairs.
locations = [latitude, longitude]

# 2. Assign the weights variable to some values.
temperatures = # an array of equal length of the locations array.

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)

# 6. Call the figure to plot the data.
fig

In [5]:
# Get the maximum temperature (remove negative temps)
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of max temperatures

# 1. Assign the locations to an array of latitude and logitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Max Temp"]

# 3. Assign the figure variable to the gmaps.figure() attribute. **Adjust center of map and zoom
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, 
                                   max_intensity=300, point_radius=4)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity

locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, 
                                   max_intensity=300, point_radius=4)
fig.add_layer(heatmap_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness

locations = city_data_df[["Lat", "Lng"]]
cloudiness = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heatmap_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, 
                                   max_intensity=300, point_radius=4)
fig.add_layer(heatmap_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of wind speed

locations = city_data_df[["Lat", "Lng"]]
wind_speed = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heatmap_layer = gmaps.heatmap_layer(locations, weights=wind_speed, dissipating=False, 
                                   max_intensity=300, point_radius=4)
fig.add_layer(heatmap_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [32]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & \
                                       (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Hilo,US,2020-04-14 04:46:26,19.73,-155.09,78.80,74,20,10.29
3,3,Rikitea,PF,2020-04-14 04:42:39,-23.12,-134.97,77.02,69,81,12.01
4,4,Negara,ID,2020-04-14 04:46:26,-8.32,114.60,84.38,68,11,7.94
5,5,Atuona,PF,2020-04-14 04:46:26,-9.80,-139.03,82.49,68,79,4.61
8,8,Busselton,AU,2020-04-14 04:46:27,-33.65,115.33,75.00,33,52,10.87
12,12,Chiredzi,ZW,2020-04-14 04:46:28,-21.05,31.67,75.24,48,0,4.12
15,15,Auki,SB,2020-04-14 04:46:29,-8.77,160.70,85.21,71,65,7.52
17,17,Vaini,TO,2020-04-14 04:46:29,-21.20,-175.20,78.80,78,40,8.05
23,23,Puerto Ayora,EC,2020-04-14 04:42:41,-0.74,-90.35,78.01,91,99,1.99
29,29,Port Augusta,AU,2020-04-14 04:46:33,-32.50,137.77,84.20,14,24,10.29

In [33]:
# Create DataFrame called hotel_df to store hotel names alongside city, country, max temp, and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp    Lat     Lng Hotel Name
2           Hilo      US     78.80  19.73 -155.09
3        Rikitea      PF     77.02 -23.12 -134.97
4         Negara      ID     84.38  -8.32  114.60
5         Atuona      PF     82.49  -9.80 -139.03
8      Busselton      AU     75.00 -33.65  115.33
12      Chiredzi      ZW     75.24 -21.05   31.67
15          Auki      SB     85.21  -8.77  160.70
17         Vaini      TO     78.80 -21.20 -175.20
23  Puerto Ayora      EC     78.01  -0.74  -90.35
29  Port Augusta      AU     84.20 -32.50  137.77

In [34]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # Use base URL to search for hotels in Paris.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [38]:
hotel_df.head(60)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Hilo,US,78.80,19.73,-155.09,Hilo Hawaiian Hotel
3,Rikitea,PF,77.02,-23.12,-134.97,Pension Maro'i
4,Negara,ID,84.38,-8.32,114.60,Jati Hotel
5,Atuona,PF,82.49,-9.80,-139.03,Villa Enata
8,Busselton,AU,75.00,-33.65,115.33,Observatory Guest House
12,Chiredzi,ZW,75.24,-21.05,31.67,The Nesbitt Arms
15,Auki,SB,85.21,-8.77,160.70,Auki Motel
17,Vaini,TO,78.80,-21.20,-175.20,Keleti Beach Resort
23,Puerto Ayora,EC,78.01,-0.74,-90.35,Finch Bay Galapagos Hotel
29,Port Augusta,AU,84.20,-32.50,137.77,Majestic Oasis Apartments
30,Kupang,ID,84.96,-10.17,123.58,Sylvia Hotel Premier Kupang
34,Buala,SB,85.10,-8.14,159.59,Maringe Lagoon Lodge
35,Mecca,SA,79.68,21.43,39.83,Al Shohada Hotel MAKKAH
41,Sijunjung,ID,81.34,-0.69,100.95,Hotel Bukik Gadang
43,Kidal,ML,80.76,18.44,1.41,
46,Port Blair,IN,84.34,11.67,92.75,Hotel Sentinel
47,Biak,ID,84.33,-0.91,122.88,Kost Ariz
48,Faanui,PF,83.12,-16.48,-151.75,Bora-Bora Pearl Beach Resort & Spa
54,Linguere,SN,79.99,15.40,-15.12,Centre Amadou Seck - Linguere
61,Avarua,CK,78.80,-21.21,-159.78,Paradise Inn
63,Ewa Beach,US,80.60,21.32,-158.01,Parkside By Gentry
66,Ko Samui,TH,84.20,9.54,99.94,"The Passage Samui Villas & Resort, Thailand"
69,Ndioum,SN,77.70,16.51,-14.65,l'hôtel samassa
72,Touros,BR,75.20,-5.20,-35.46,INN NEW HORIZON
76,Mackay,AU,82.40,-21.15,149.20,International Lodge Motel
77,Kapaa,US,78.80,22.08,-159.32,Sheraton Kauai Resort at Coconut Beach
83,Saint-Philippe,RE,81.00,-21.36,55.77,"Chambres d'hôte ""La Trinité"""
84,Victoria,HK,75.99,22.29,114.16,Mini Hotel Central
97,Port Lincoln,AU,75.27,-34.73,135.87,Port Lincoln Hotel
103,Port-Gentil,GA,80.80,-0.72,8.78,Fengshui Residence
104,Kiama,AU,78.01,-34.68,150.87,The Sebel Kiama Harbourside
105,Gweta,BW,75.60,-20.18,25.23,Gweta Lodge
111,Sibolga,ID,89.67,1.74,98.78,Hotel Syariah CN Darussalam
112,Korla,CN,77.52,41.76,86.15,Gulisitan Hotel
118,Inhambane,MZ,75.20,-23.86,35.38,MHL Turismo SA
121,Moussoro,TD,79.23,13.64,16.49,Pharmacie alnadja Moussoro
123,Celestun,MX,79.34,20.87,-90.40,Posada Lilia
127,Saint Pete Beach,US,80.60,27.73,-82.74,TradeWinds Island Grand Resort
128,Pochutla,MX,78.01,15.74,-96.47,Hotel Posada San Jose
136,Maceio,BR,75.20,-9.67,-35.74,Mercure Maceio Pajucara Hotel
137,Sabha,LY,76.06,27.04,14.43,محطة ام الارانب -سبها مواصلات
141,Carnarvon,AU,82.40,-24.87,113.63,Hospitality Carnarvon
142,Flinders,AU,79.00,-34.58,150.86,Shellharbour Resort & Conference Centre
150,Changde,CN,75.42,29.05,111.68,Kangshida Hotel
154,Bajil,YE,82.94,15.06,43.29,فندق الصقر السياحي
157,Matara,LK,89.89,5.95,80.54,Amaloh Boutique Resort
158,Noumea,NC,82.40,-22.28,166.46,Hôtel Le Lagon
160,Geraldton,AU,78.80,-28.77,114.60,Broadwater Mariner Resort
164,Bandarbeyla,SO,83.79,9.49,50.81,REER XOOSHLE GROUP
165,Yulara,AU,89.60,-25.24,130.99,Desert Gardens Hotel - Ayers Rock Resort
176,Nizwa,OM,81.88,22.93,57.53,Orient Apartments
178,Taunggyi,MM,84.87,20.78,97.03,True Treasure Hotel
181,Tessalit,ML,77.77,20.20,1.01,
183,Ballina,AU,80.60,-28.87,153.57,Ramada Hotel & Suites by Wyndham Ballina Byron
184,Moju,BR,78.80,-1.88,-48.77,HOTEL MARTINS
186,Nabire,ID,85.39,-3.37,135.48,Hotel Nusantara Nabire
187,Mahebourg,MU,81.00,-20.41,57.70,Shandrani Beachcomber Resort & Spa
191,Broken Hill,AU,77.00,-31.95,141.43,Daydream Motel & Cottages
192,Mongo,TD,81.28,12.18,18.69,
193,Kirakira,SB,85.01,-10.45,161.92,SanBiz Lodge

In [36]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [37]:
# Heatmap of max temperatures

locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heatmap_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heatmap_layer)
fig.add_layer(marker_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))